### ISSUE TITLE
[BUG] path existence is relative to run script, not config file location

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/dataconfig#16]
**Describe the bug**
It seems that filepath validation is not relative to the location of the configuration file. This isn't a problem of dataconfig, but rather pydantic's 'FilePath' validator. Perhaps the easiest solution is a custom RelativeFilePath validator?

Assuming the following file structure:

run_script.py
rules.yaml
model/
|-- config.yaml
|-- techs.yaml

It should be possible to point to `techs.yaml` from `config.yaml` (```techs: techs.yaml```), and it be valid for the rule:

```
techs:
  type: FilePath
  doc: Path to techs data configuration
```

However, on validating `config.yaml` in `run_script.py`, it fails. Instead, it requires the filepath in `config.yaml` to be `model/techs.yaml`.

 **Minimal reproducible example**
Outline steps to reproduce the behaviour with examples:
rules.yaml:
```yaml
techs:
  type: FilePath
  doc: Path to techs data configuration
```

config.yaml:
```yaml
techs: techs.yaml
```

run_script.py:
```python
import dataconfig as dc
rules_yaml = dc.helpers.read_yaml('rules.yaml')
rules = get_config_t(rules_yaml)
rules.from_yaml('model/config.yaml')
```

error:
```python
techs
  file or directory at path "techs.yaml" does not exist (type=value_error.path.not_exists; path=techs.yaml)
```

**Platform details:**
 - OS: MacOS
 - Python version: 3.8.2
 - Python distribution: standard

**Comment by suvayu** [comment]
I think the solution to this is a custom type.  If you look at the source for [`FilePath`](https://github.com/samuelcolvin/pydantic/blob/44616e35cb0ddd97af07b95d7209176a29bfea49/pydantic/types.py#L542-L558), you'll see `__get_validators__()` includes [`validators.path_exists_validator`](https://github.com/samuelcolvin/pydantic/blob/44616e35cb0ddd97af07b95d7209176a29bfea49/pydantic/validators.py#L389-L393).  The new custom type should replace this with something that uses the relative path the way we want to.

Now, that piece of code could be a bit fiddly because relative paths in Python are always relative to the script that's running, and we have no control over where the config file might be wrt to the script.  Typically one would solve this by anchoring against the `__file__` attribute, but that's most likely not possible here because there is no Python file, everything is generated on the fly!  I could try "injecting" it in the factory, but I'm not sure how easy/difficult that might be.

The next steps are:
1. write a custom type with a custom validator
2. use this validator to inspect whether `__file__` is accessible, and what is the reported by the `os` module for different relative positions
    - same level as script
    - in a sub-directory below script
    - in a different parallel directory other than script
3. learnings from the above will tell us if the factory needs to be modified, or if `os` can provide us the desired information.

I would need help here.
